[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
  cloudName = "dscuv3gae"
  deliveryType = "upload"
[[redirects]]
  from = "/review"
  to = "https://www.google.de/search?q=marina+schmid+fotografie&source=hp&ei=xzajY4STJdKTxc8P2JGcqAY&iflsig=AJiK0e8AAAAAY6NE14wVVxzKvhjAHG85_xlPWJJbfSPB&ved=0ahUKEwjEkv2Uk4v8AhXSSfEDHdgIB2UQ4dUDCAo&uact=5&oq=marina+schmid+fotografie&gs_lcp=Cgdnd3Mtd2l6EAMyBwgAEB4QogQyBQgAEKIEMgUIABCiBDoLCAAQgAQQsQMQgwE6DQguELEDEMcBENEDEAo6EQguEIAEELEDEIMBEMcBENEDOggILhCxAxCDAToOCC4QgAQQsQMQxwEQ0QM6BQgAEIAEOggILhCABBDUAjoICAAQsQMQgwE6DgguEIAEEMcBENEDENQCOggIABCABBCxAzoFCC4QgAQ6CwguEIAEELEDENQCOhEILhCABBCxAxDHARDRAxDUAjoICC4QgAQQsQM6DgguEIAEELEDEIMBENQCOgsILhCABBCxAxCDAToOCC4QrwEQxwEQsQMQgAQ6DgguEIAEELEDEMcBEK8BOhAILhCvARDHARCxAxCABBANOgcILhCABBANOgoILhCxAxCABBANOhAILhCABBCxAxDHARCvARANOgoILhCABBCxAxANOg0ILhCABBCxAxCDARANOg0ILhCABBCxAxDUAhANOg0ILhCABBDHARCvARANOgsILhCABBDHARCvAToHCC4QgAQQCjoGCAAQFhAeOgkIABAWEB4Q8QQ6CAgAEAgQHhANOgcIIRCgARAKOgUIIRCgAVAAWNcYYMUZaABwAHgAgAF2iAGXD5IBBDIwLjSYAQCgAQE&sclient=gws-wiz#lrd=0x2a5eae6edccb992d:0x90c4bae1d3eb9178,3,,,"
  status = 302